config/routes.rb
PitchOverflow::Application.routes.draw do

  resources :pitches, only: [:index, :show, :new, :create] do
    resources :reactions, only: [:create]
  end

  root :to => "pitches#index"

  post 'pitches/upvote' => 'pitches#upvote'
  post 'pitches/downvote' => 'pitches#downvote'

  get "/auth/:provider/callback" => "sessions#create_from_github"
  get "/auth/failure" => "sessions#failure_from_github"
  get "/signout" => "sessions#destroy"#, :as => :signout
  get "/auth/github" => "sessions#new", as: :omniauth

  

  mount JasmineRails::Engine => "/specs" if defined?(JasmineRails)
end

app/models/pitch.rb
class Pitch < ActiveRecord::Base

  before_save :titleize_title

  has_many :reactions
  has_many :votes
  belongs_to :user
  validates_presence_of :title
  validates_presence_of :content
  validates_presence_of :user

  def score
    votes.select {|vote| vote.upvote == true }.length - votes.select {|vote| vote.upvote == false }.length
  end

  private

  def titleize_title
    self.title = title.titleize
  end
end

app/models/reaction.rb
class Reaction < ActiveRecord::Base
  belongs_to :pitch
  belongs_to :user

  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :pitches
  has_many :reactions
  has_many :votes

  validates_presence_of :username, :provider, :uid

  def upvote!(pitch)
    vote = self.votes.find_or_create_by_pitch_id(pitch.id)
    vote.update_attribute("upvote", true)
  end

  def downvote!(pitch)
    vote = self.votes.find_or_create_by_pitch_id(pitch.id)
    vote.update_attribute("upvote", false)
  end

  def self.create_from_omniauth(omniauth)
    User.new.tap do |user|
      user.uid = omniauth["uid"]
      user.username = omniauth["info"]["nickname"]
      user.provider = omniauth['provider']
      # user.email = omniauth["info"]["email"]
      user.save!
    end
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :user
  belongs_to :pitch

  validates_presence_of :user, :pitch
  validates_associated :user, :pitch
  validates_inclusion_of :upvote, :in => [true, false]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :require_login, only: [:create, :upvote, :downvote]

  private

  def require_login
    return if current_user
    if request.xhr?
      render status: 302, :text => omniauth_path
    else
      redirect_to omniauth_path
    end
  end
end

app/controllers/pitches_controller.rb
class PitchesController < ApplicationController

  before_filter :find_pitch, only: [:upvote, :downvote, :show]
  def index
    @pitches = Pitch.all.sort { |x, y| x.score <=> y.score }.reverse
  end

  def show
  end

  def new
    @pitch = Pitch.new
  end

  def create
    @pitch = current_user.pitches.create(pitch_params)
    redirect_to pitch_path(@pitch)
  end

  def upvote
    current_user.upvote!(@pitch)
    render partial: 'score', locals: { score: @pitch.score }
  end

  def downvote
    current_user.downvote!(@pitch)
    render partial: 'score', locals: { score: @pitch.score }
  end

  private

  def pitch_params
    params.require(:pitch).permit(:title, :content)
  end

  def find_pitch
    @pitch = Pitch.find(params[:id])
  end
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController

  def create
    debugger;
    pitch = Pitch.find(params[:pitch_id])
    reaction = pitch.reactions.create(reaction_params)
    reaction.user = current_user
    reaction.save
    render partial: "pitches/reaction", locals: { reaction: reaction }
  end
  private

  def reaction_params
    params.require(:reaction).permit(:content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create_from_github
    omniauth = request.env["omniauth.auth"]
    @user = User.find_by_uid(omniauth["uid"]) || User.create_from_omniauth(omniauth)
    session[:user_id] = @user.id

    redirect_to root_path, :notice => "Welcome, #{@user.username}"  
  end

  def failure_from_github
    flash[:error] = "Error logging in with GitHub. #{params[:message]}"
    redirect_to root_path
  end


  def destroy
    session.clear
    redirect_to root_url, :notice => "Signed Out!"
  end

  def new
    redirect_to omniauth_path
  end

end
  

app/helpers/application_helper.rb
module ApplicationHelper
  def sign_in?
    session[:user_id]
  end

  def current_user
    return unless session[:user_id]
    user = User.find(session[:user_id])
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_top_nav.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to 'Pitch Overflow', root_path %></a></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li class="divider"></li>
      <li><%= link_to 'All Pitches', pitches_path %></li>
    </ul>
    <ul class="right">
      <li class="divider"></li>
      <% unless sign_in? %>
        <li><%= link_to 'Login', omniauth_path %></li>
      <% else %>
        <li class="divider"></li>
        <li class="has-form">
          <%= link_to "New Pitch!", new_pitch_path, class: 'small button radius' %>
        </li>
        <li class="divider"></li>
        <li class="has-dropdown">
          <a href="#"><%= current_user.username %></a>
          <ul class="dropdown">
            <li><%= link_to 'Logout', signout_path %></li>
          </ul>
        </li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>PitchOverflow</title>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/top_nav' %>

    <div class="row">
      <div class="small-12 columns">
        <%= yield %>
      </div>
    </div>

  </body>

</html>

app/views/pitches/_reaction.html.erb
<div id="reaction-<%= reaction.id %>" class='panel'>
  <blockquote>
  <%= reaction.content %>

  <cite><%= reaction.user.username %>, <%= time_ago_in_words reaction.created_at %> ago</cite>
  </blockquote>
</div>

app/views/pitches/_score.html.erb
<h2 id='score'><%= score %></h2>

app/views/pitches/index.html.erb
<h1>Top Pitches</h1>

<% @pitches.each do |pitch| %>
  <div class="row panel">

    <div class="small-1 columns">
      <h3 class="subheader"><%= pitch.score %></h3>
    </div>
    <div class="small-11 columns">
      <h3 class="subheader"><%= link_to pitch.title, pitch_path(pitch) %></h3>
    </div>

  </div>
  <br />
<% end %>

app/views/pitches/new.html.erb
<h1>Make Your Pitch</h1>

<div>
  <%= form_for @pitch do |f| %>
    <%= f.text_field :title, placeholder: "Pitch Title" %>
    <%= f.text_area :content, placeholder: "Pitch Content" %>
    <%= f.submit "Pitch it!", class: 'large button expand' %>
  <% end %>
</div>

app/views/pitches/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <div class="small-1 columns">
      <br>
      <br>
      <br>
      <%= button_to "+1", pitches_upvote_path(:id => params[:id]), id: "upvote", remote: true, class: "button success small radius"  %>
      <div id='pitch-score'>
        <%= render partial: "score", locals: { score: @pitch.score } %>
      </div>
      <%= button_to "-1", pitches_downvote_path(:id => params[:id]), id: "downvote", remote: true, class: "button alert small radius disabled", disabled: true%>
    </div>
    <div class="small-11 columns">
      <h2 class"subheader"><%= @pitch.title %></h2>
      <h6 class='subheader'>by <%= @pitch.user.username %>, <%= time_ago_in_words @pitch.created_at %> ago</h6>
      <h2 class="subheader"><%= @pitch.content %></h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <div id="pitch_reactions">
      <%= render partial: "reaction", collection: @pitch.reactions %>
    </div>
    <hr>
    <h3>Your reaction:</h3>
    <%= form_for [@pitch, @pitch.reactions.build], remote: true do |f| %>
      <%= f.text_area :content %>
      <%= f.submit id: "submit_reaction", value: 'Post Your Reaction', class: 'submit expand button small radius' %>
    <% end %>
  </div>
</div>